### ISSUE TITLE
güncelleme gelecek mi?

### ISSUE THREAD

**Issue by okyayaykut** [alisaitteke/seatmap-canvas#2]
Merhaba, kütüphane için öncelikle teşekkür ederim. Uygulama hakkında bi kaç sorum var.

1) sahne gibi mekanlarda bulunan yerlerin gösterimi nasıl yapabiliriz?
2) Mobil cihazlarda zoom out yaparken çok fazla uzaklaşma oluyor ve zoom out'u kapatma gibi şansımız yok mu?

**Comment by alisaitteke** [comment]
Merhaba,

Gec mesaj icin kusura bakmayin.
Bir guncelleme yapmayi dusunuyorum yakin zamanda. Bug fix ve Reactjs, Angular ve Vue icin.
