### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by thvroyal** [alisaitteke/seatmap-canvas#60]
**Describe the bug**
When installing in the Typescript project, I encountered the following issue: 
`Could not find a declaration file for module '@alisaitteke/seatmap-canvas'.`

**To Reproduce**
1. Install this lib through `yarn`
2. Import `SeatMapCanvas` in the typescript file

**Expected behavior**
The module has a properly declared file

**Screenshots**
<img width="581" alt="image" src="https://github.com/alisaitteke/seatmap-canvas/assets/52320573/48ef0f63-3e93-4907-82c3-3f0110bcedd7">

**Additional context**
I tried to find the root cause, then I saw you declare the `types` field in `package.json`: ` "types": "dist/index.d.ts",`. But in the node_modules when I install the module, the path of the declaration file is `dist/type.d.ts` as below:

<img width="330" alt="image" src="https://github.com/alisaitteke/seatmap-canvas/assets/52320573/897a7d9f-d164-4c31-9799-c4a940f7cf62">

So we need to correct this path, if you agree, I can create the PR to resolve it.

**Comment by alisaitteke** [comment]
@thvroyal hi, thank you for your report. If you create a PR I'll approve it right away.

**Comment by Crhis35** [comment]
> @thvroyal hi, thank you for your report. If you create a PR I'll approve it right away.

Can you give me access to create the pr?

**Comment by thvroyal** [comment]
Thanks @alisaitteke, let me do it
