### ISSUE TITLE
Create seating plan

### ISSUE THREAD

**Issue by arashsaffari** [alisaitteke/seatmap-canvas#8]
Thanks for the great library.it is very helpful.

How do you create the maps in JSON file? is there a tool for that or you have to create Manuel?

**Comment by arashsaffari** [comment]
any ideas?

**Comment by arashsaffari** [comment]
> Thanks for the great library.it is very helpful.
> 
> How do you create the maps in JSON file? is there a tool for that or you have to create Manuel?

????

**Comment by alisaitteke** [comment]
Hi @arashsaffari.

There is no JSON crator GUI. Maybe we can do that in the future.
So you have to create manuel (api base or static) at this version.
