### ISSUE TITLE
How do I use it in Vue or React

### ISSUE THREAD

**Issue by Z1oftheKill** [alisaitteke/seatmap-canvas#9]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Z1oftheKill** [comment]
I want to use it in a react or vue project, but don't know how to import it

**Comment by alisaitteke** [comment]
Hi,
I want to make it too. I hope I can do that asap. Depend of my free time :/

**Comment by JorgePAJ** [comment]
This is library is exactly what ive been looking for, but react support is indispensable :(, hope this projects continue to advance! there is no open source alternatives with this quality, great work!

**Comment by alisaitteke** [comment]
Hi @JorgePAJ, finally!

https://github.com/alisaitteke/seatmap-canvas-react
